export type { MarivoBridgeSet } from './bridges.ts'
export { createMarivoBridgeSet } from './bridges.ts'
export * from './compatibility.ts'
export * from './datasource/index.ts'
export * from './disclosure/index.ts'
export * from './environment/index.ts'
export * from './evidence/index.ts'
export type { Config as PluginConfig } from './plugin.ts'
export { apply, Config, inject, installMarivoPlugin, name } from './plugin.ts'
export * from './report/index.ts'
