export const browserStyles = `
.sb-dialog{--sb-bg:#fff;--sb-soft:#f5f7f9;--sb-text:#182a33;--sb-muted:#627580;--sb-border:#dce4e8;--sb-accent:#087b70;color:var(--sb-text);background:var(--sb-bg);border:1px solid var(--sb-border);border-radius:16px;width:calc(100vw - 48px);max-width:1500px;height:calc(100dvh - 64px);max-height:960px;padding:0;box-shadow:0 28px 100px #0003;pointer-events:auto;font:14px/1.55 system-ui,sans-serif;overflow:hidden}
.sb-expression{margin:12px 0;min-width:0}.sb-expression-heading{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.sb-expression-code{position:relative}.sb-dialog .sb-expression-copy{position:absolute;right:8px;top:8px;display:grid;place-items:center;width:30px;height:30px;padding:5px;border:0;color:var(--sb-muted);background:transparent}.sb-expression pre{padding:16px 48px 16px 16px;border:1px solid var(--sb-border);background:var(--sb-bg);border-radius:8px;overflow:auto;max-width:100%;white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.7 ui-monospace,monospace;color:var(--sb-accent)}.sb-expression-bindings{font-size:12px;overflow-wrap:anywhere}.sb-expression p{font-size:12px}
.sb-detail h2{overflow-wrap:anywhere;min-width:0}
.sb-computation{margin:20px 0;padding:18px;border:1px solid var(--sb-border);border-radius:12px;background:var(--sb-soft);overflow-wrap:anywhere}.sb-computation-heading{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.sb-computation h3{margin:0}.sb-referenced-definitions>h3,.sb-definition-sources>h3{margin-top:24px;margin-bottom:10px}.sb-definition-entry{padding:14px 0;border-top:1px solid var(--sb-border)}.sb-definition-entry-heading{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.sb-definition-entry h4{margin:0;min-width:0;font-size:13px}.sb-definition-entry .sb-formula{margin:8px 0;font-weight:400;font-size:13px}.sb-definition-entry .sb-expression{margin:8px 0}.sb-definition-entry .sb-expression pre{margin:8px 0}.sb-formula-term{display:inline-block;max-width:100%}.sb-definition-sources>div{display:flex;align-items:baseline;gap:12px;flex-wrap:wrap;padding:6px 0}.sb-temporal h4{font-size:12px;margin:12px 0 6px}.sb-formula{font-weight:600;font-size:15px}.sb-dialog details>summary{cursor:pointer;padding:8px 0;color:var(--sb-accent)}.sb-dialog .sb-definition-link{border:0;padding:2px 4px;text-align:left;color:var(--sb-accent);overflow-wrap:anywhere;max-width:100%;background:transparent}.sb-temporal{margin-top:12px}
.sb-dialog::backdrop{background:#102a3a66;backdrop-filter:blur(4px)}
.sb-dialog *{box-sizing:border-box}.sb-shell{height:100%;display:flex;flex-direction:column}.sb-dialog button,.sb-dialog input,.sb-dialog select{font:inherit;color:inherit}.sb-dialog button{cursor:pointer;background:var(--sb-bg);border:1px solid var(--sb-border);border-radius:7px;padding:6px 10px}.sb-dialog button:hover{background:var(--sb-soft)}.sb-dialog button:disabled{cursor:default;opacity:.5}.sb-dialog :focus-visible{outline:2px solid var(--sb-accent);outline-offset:3px}.sb-dialog button[aria-pressed=true],.sb-dialog button[aria-selected=true]{border-color:var(--sb-accent);color:var(--sb-accent);background:var(--sb-soft)}
.sb-header{display:flex;align-items:center;flex-wrap:wrap;gap:12px;padding:18px 22px;border-bottom:1px solid var(--sb-border)}.sb-header h1{font-size:20px;margin:0 16px 0 0}.sb-header select{max-width:300px;padding:7px;border:1px solid var(--sb-border);border-radius:6px;background:var(--sb-bg)}.sb-header .sb-close{margin-left:auto}.sb-meta{padding:8px 22px;background:var(--sb-soft);display:flex;flex-wrap:wrap;gap:8px 20px;font-size:12px;color:var(--sb-muted);overflow-wrap:anywhere}.sb-status{padding:10px 22px;border-bottom:1px solid var(--sb-border);background:var(--sb-soft)}
.sb-columns{display:grid;grid-template-columns:170px minmax(230px,320px) minmax(0,1fr);flex:1;min-height:0}.sb-nav,.sb-list,.sb-detail{overflow:auto;min-width:0;padding:18px}.sb-nav,.sb-list{border-right:1px solid var(--sb-border)}.sb-nav h2{font-size:12px;color:var(--sb-muted);margin:0 0 12px;letter-spacing:.08em}.sb-nav button{display:flex;justify-content:space-between;width:100%;text-align:left;margin-bottom:5px;border-color:transparent}.sb-nav select{width:100%;margin:0 0 24px;padding:7px;background:var(--sb-bg);border:1px solid var(--sb-border);border-radius:6px}
.sb-search{width:100%;padding:9px 10px;border:1px solid var(--sb-border);border-radius:7px;background:var(--sb-bg)}.sb-count{font-size:12px;color:var(--sb-muted);margin:10px 0}.sb-objects{list-style:none;padding:0;margin:0}.sb-objects button{display:block;text-align:left;width:100%;padding:12px;margin-bottom:8px;overflow-wrap:anywhere}.sb-object-title{display:flex;gap:8px;align-items:start;justify-content:space-between}.sb-badge{font-size:11px;white-space:nowrap;padding:1px 6px;border-radius:4px;background:var(--sb-soft);color:var(--sb-muted);font-weight:400}.sb-summary{display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;color:var(--sb-muted);font-size:12px;margin:5px 0}.sb-ref{font:11px/1.6 ui-monospace,monospace;overflow-wrap:anywhere;color:var(--sb-muted)}.sb-pager,.sb-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:12px 0}.sb-pager{justify-content:space-between;font-size:12px}
.sb-detail{padding:24px 28px}.sb-detail h2{font-size:25px;line-height:1.3;margin:10px 0}.sb-detail h3{font-size:14px;margin:24px 0 10px}.sb-detail p{white-space:pre-wrap;overflow-wrap:anywhere}.sb-tabs{display:flex;gap:8px;border-bottom:1px solid var(--sb-border);padding:10px 0;margin:18px 0}.sb-fields{display:grid;grid-template-columns:minmax(100px,30%) minmax(0,1fr);margin:0}.sb-fields dt,.sb-fields dd{padding:10px 0;border-bottom:1px solid var(--sb-border);margin:0;white-space:pre-wrap;overflow-wrap:anywhere}.sb-fields dt{color:var(--sb-muted);padding-right:14px}.sb-muted{color:var(--sb-muted);font-size:12px}.sb-empty{padding:50px 24px;text-align:center;color:var(--sb-muted)}.sb-relation-list{list-style:none;padding:0}.sb-relation-list li{display:flex;align-items:center;gap:8px;padding:8px 0;border-bottom:1px solid var(--sb-border);flex-wrap:wrap}.sb-relation-list button{overflow-wrap:anywhere;text-align:left}.sb-graph svg{width:100%;border:1px solid var(--sb-border);background:var(--sb-soft);border-radius:8px;touch-action:none}.sb-graph [role=button]{cursor:pointer}.sb-back-list{display:none}
@media(prefers-color-scheme:dark){.sb-dialog{--sb-bg:#182127;--sb-soft:#202d34;--sb-text:#e4edf1;--sb-muted:#9baeb9;--sb-border:#35464f;--sb-accent:#39b8a8}}
@media(max-width:850px){.sb-dialog{width:calc(100vw - 16px);height:calc(100dvh - 16px);border-radius:10px}.sb-columns{grid-template-columns:130px minmax(0,1fr)}.sb-detail{display:none}.sb-columns.sb-has-selection{display:block;overflow:auto}.sb-has-selection .sb-nav,.sb-has-selection .sb-list{display:none}.sb-has-selection .sb-detail{display:block}.sb-back-list{display:inline-block}.sb-header{padding:12px}.sb-header h1{font-size:17px}.sb-header select{max-width:190px}.sb-detail{padding:18px}.sb-fields{grid-template-columns:110px minmax(0,1fr)}}
`
