ReportData.register('dsh-starter-placeholder-dataset', {
  schema: 'dsh-data-analysis-dataset/v1',
  dataset_id: 'dsh-starter-placeholder-dataset',
  emitted_at: '2026-08-31T12:00:00Z',
  source: {
    kind: 'marivo_artifact',
    artifact: {
      session_id: 'starter-session-placeholder',
      ref: 'starter-artifact-placeholder',
      kind: 'metric_frame',
      artifact_schema_version: 'analysis-artifact/v13',
      content_hash: null,
      created_at: '2026-08-31T11:00:00Z',
      row_count: 4,
      evidence_status: 'partial',
      finding_count: 1,
    },
    quality_summary: {
      coverage: 0.75,
      null_rate: 0,
      sample_size: 4,
      sample_coverage_min: 0.75,
      sample_coverage_avg: 0.75,
      sample_coverage_partial_buckets: 1,
      zero_denominator_rows: 0,
      evaluated_check_count: 2,
      failed_check_count: 0,
      warning_check_count: 1,
    },
    issues: [
      {
        category: 'data_quality',
        kind: 'starter-coverage-warning',
        severity: 'warning',
        check_id: 'starter-coverage',
        expectation: 'Replace this synthetic fixture with checked report data',
        repair: null,
      },
    ],
    issues_omitted: 0,
    lineage: {
      external_inputs: [],
      external_inputs_omitted: 0,
      steps: [],
      steps_omitted: 0,
    },
    revalidation: {
      status: 'checked',
      result: 'stale',
      semantic_status: 'stale',
      evidence_status: 'partial',
      dependency_status: 'stale',
      checked_at: '2026-08-31T12:00:00Z',
      issues: [],
      issues_omitted: 0,
    },
  },
  table: {
    total_rows: 4,
    written_rows: 4,
    omitted_rows: 0,
    semantic_shape: 'time_series',
    columns: [
      {
        name: 'month',
        dtype: 'string',
        artifact_dtype: 'string',
        contains_null: false,
        nullable: false,
        role: 'time',
      },
      {
        name: 'revenue',
        dtype: 'float64',
        artifact_dtype: 'float64',
        contains_null: false,
        nullable: false,
        role: 'measure',
      },
    ],
    rows: [
      ['2026-01', 102],
      ['2026-02', 118],
      ['2026-03', 126],
      ['2026-04', 141],
    ],
  },
})
