ReportTrace.register('dsh-starter-placeholder-trace', {
  schema: 'dsh-data-analysis-session-trace/v1',
  trace_id: 'dsh-starter-placeholder-trace',
  emitted_at: '2026-08-31T12:00:00Z',
  session_id: 'starter-session-placeholder',
  report_artifact_refs: ['starter-artifact-placeholder'],
  artifacts: [
    {
      ref: 'starter-artifact-placeholder',
      family: 'MetricFrame',
      semantic_shape: 'time_series',
      created_at: '2026-08-31T11:00:00Z',
      produced_by_run: 'starter-run-placeholder',
      analysis_purpose: 'Reference-only component journey',
      row_count: 4,
      materialization: 'materialized',
      evidence: {
        status: 'partial',
        finding_count: 1,
        digest_present: true,
        digest_item_count: 1,
        omitted_item_count: 0,
      },
      quality: {
        coverage: 0.75,
        null_rate: 0,
        sample_size: 4,
        sample_coverage_min: 0.75,
        sample_coverage_avg: 0.75,
        sample_coverage_partial_buckets: 1,
        zero_denominator_rows: 0,
        evaluated_check_count: 2,
        failed_check_count: 0,
        warning_check_count: 1,
      },
      issue_counts: { warning: 1, blocking: 0 },
    },
  ],
  runs: [
    {
      run_id: 'starter-run-placeholder',
      lifecycle: 'succeeded',
      capability_id: 'starter.observe',
      analysis_purpose: 'Reference-only component journey',
      input_artifact_refs: [],
      started_at: '2026-08-31T10:59:00Z',
      finished_at: '2026-08-31T11:00:00Z',
      output_artifact_ref: 'starter-artifact-placeholder',
      output_mode: 'produced',
    },
  ],
  edges: [
    {
      kind: 'produces',
      run_id: 'starter-run-placeholder',
      artifact_ref: 'starter-artifact-placeholder',
    },
  ],
  queries: [
    {
      run_id: 'starter-run-placeholder',
      query_id: 'starter-query-placeholder',
      datasource: 'starter-warehouse',
      dialect: 'trino',
      sql: 'SELECT\n  month,\n  SUM(revenue) AS revenue\nFROM starter.orders\nWHERE month >= ?\nGROUP BY month\nORDER BY month',
      digest: 'starter-digest-placeholder',
      status: 'succeeded',
      duration_ms: 640,
      row_count: 4,
      started_at: '2026-08-31T10:59:01Z',
      finished_at: '2026-08-31T10:59:01.640Z',
      output_artifact_ref: 'starter-artifact-placeholder',
    },
  ],
  root_run_ids: ['starter-run-placeholder'],
  head_artifact_refs: [],
  failed_run_ids: [],
  incomplete_run_ids: [],
  boundary_artifact_refs: ['starter-artifact-placeholder'],
  boundary_run_ids: [],
  truncated: true,
  projection: {
    run_arguments: 'omitted',
    failure_values: 'omitted',
    query_bind_values: 'omitted',
  },
  read_boundaries: [
    'semantic_authority_not_checked',
    'datasource_freshness_not_checked',
    'report_entailment_not_checked',
  ],
})
