/** Host-only chrome. Portable reports keep their own independent stylesheet. */
export const rightTabStyles = `
.rt-page{height:100%;width:100%;min-width:0;overflow:auto;padding:16px;box-sizing:border-box;color:var(--dsw-alias-label-primary,#182a33);background:var(--dsw-alias-bg-base,#fff);container-type:inline-size;font:14px/1.6 system-ui,sans-serif}
.rt-page *{box-sizing:border-box}.rt-page h2{font-size:18px;overflow-wrap:anywhere}.rt-page .rt-heading{margin:0 0 4px}.rt-heading-row{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:4px}.rt-page .rt-heading-row .rt-heading{margin:0}.rt-heading-row>button{flex:none}.rt-caption{color:var(--dsw-alias-label-secondary,#627580);font-size:12px;margin:0 0 16px;overflow-wrap:anywhere}
.rt-toolbar{display:flex;flex-wrap:wrap;align-items:center;gap:8px;padding-bottom:12px;border-bottom:1px solid var(--dsw-alias-border-l2,#dce4e8);margin-bottom:16px}
.rt-page button,.rt-page select,.rt-page input{font:inherit;color:inherit;max-width:100%}.rt-page button{cursor:pointer;border:1px solid var(--dsw-alias-border-l2,#dce4e8);background:var(--dsw-alias-bg-base,#fff);border-radius:7px;padding:6px 10px}.rt-page button:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover,#edf4f3)}.rt-page button:disabled{opacity:.5;cursor:default}.rt-page :focus-visible{outline:2px solid var(--dsw-alias-state-business-primary,#087b70);outline-offset:3px}
.rt-page select{padding:8px;border:1px solid var(--dsw-alias-border-l2,#dce4e8);border-radius:7px;background:var(--dsw-alias-bg-base,#fff)}.rt-page [role=alert]{color:var(--dsw-alias-state-warn-label,#b14927);overflow-wrap:anywhere}.rt-notice{padding:12px;border:1px solid var(--dsw-alias-border-l2,#dce4e8);border-radius:8px;background:var(--dsw-alias-bg-module-platform,#f5f7f9)}
.rt-page .pd-catalog{padding:0;overflow:auto}.rt-page .pd-history{position:static;max-height:300px;border:1px solid var(--dsw-alias-border-l2,#dce4e8);border-radius:8px;margin-bottom:16px;width:100%}
.rt-page .sb-embedded{--sb-bg:var(--dsw-alias-bg-base,#fff);--sb-soft:var(--dsw-alias-bg-module-platform,#f5f7f9);--sb-text:var(--dsw-alias-label-primary,#182a33);--sb-muted:var(--dsw-alias-label-secondary,#627580);--sb-border:var(--dsw-alias-border-l2,#dce4e8);--sb-accent:#087b70;height:100%;min-height:420px;color:var(--sb-text);background:var(--sb-bg)}
.rt-page .sb-columns{grid-template-columns:110px minmax(140px,1fr) minmax(180px,1.4fr)}.rt-page .sb-meta{overflow-wrap:anywhere}
.rt-semantic-filters{display:none}.rt-datasource{display:grid;gap:16px;max-width:900px}.rt-datasource label{display:grid;gap:6px;font-weight:500}.rt-datasource .mc-props{margin:0}.rt-datasource-actions{display:flex;flex-wrap:wrap;gap:8px}
@container(max-width:650px){.rt-page .rt-semantic-filters{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:12px}.rt-semantic-filters label{display:grid;gap:4px;flex:1;min-width:100px}.rt-page .sb-columns{display:block;overflow:auto}.rt-page .sb-nav{display:none}.rt-page .sb-detail{display:none}.rt-page .sb-has-selection .sb-list{display:none}.rt-page .sb-has-selection .sb-detail{display:block}.rt-page .sb-back-list{display:inline-block}.rt-page .pr-reader{padding:24px 4px}.rt-page .pr-reader h1{font-size:25px}.rt-page .pr-block-metric{padding:14px}.rt-page .pr-metric-value{font-size:clamp(18px,7cqi,30px)}.rt-page .sb-header{flex-wrap:wrap}}
`
